# Generated by Django 3.0.3 on 2020-05-02 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='vission',
            new_name='vision',
        ),
    ]
